// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlt-8gZwJFGiHL6EwsdxbB4DXfNFIJVio',
    appId: '1:1087444261879:web:1663e1e81521d6db53ecf2',
    messagingSenderId: '1087444261879',
    projectId: 'lrt-mileage-tracking',
    authDomain: 'lrt-mileage-tracking.firebaseapp.com',
    databaseURL: 'https://lrt-mileage-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lrt-mileage-tracking.firebasestorage.app',
    measurementId: 'G-W5K5SE13BY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlt-8gZwJFGiHL6EwsdxbB4DXfNFIJVio',
    appId: '1:1087444261879:web:1663e1e81521d6db53ecf2',
    messagingSenderId: '1087444261879',
    projectId: 'lrt-mileage-tracking',
    authDomain: 'lrt-mileage-tracking.firebaseapp.com',
    databaseURL: 'https://lrt-mileage-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lrt-mileage-tracking.firebasestorage.app',
    measurementId: 'G-W5K5SE13BY',
  );
}
